# Generated by Django 4.0.2 on 2022-02-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=150)),
                ('workmode', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=500)),
                ('skills', models.CharField(max_length=500)),
            ],
        ),
    ]
