# Generated by Django 4.0.2 on 2022-02-12 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_remove_recruiter_post_skills_skills_reqd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eligible_Colleges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiter_post')),
            ],
        ),
    ]
